
from flask import Flask, render_template, request, jsonify, send_file
from flask_cors import CORS
import pymysql
from datetime import datetime, timedelta
from decimal import Decimal, ROUND_HALF_UP
import os
import textwrap
import smtplib
from email.message import EmailMessage

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas

# Optional SMS via Twilio
try:
    from twilio.rest import Client
    TWILIO_AVAILABLE = True
except ImportError:
    TWILIO_AVAILABLE = False


app = Flask(__name__)
CORS(app)

PDF_FOLDER = "generated_pdfs"
os.makedirs(PDF_FOLDER, exist_ok=True)

# =========================
# BUSINESS CONFIG
# =========================
BUSINESS_INFO = {
    "name": "P-HUB",
    "address": "Hyderabad, India",
    "phone": "+916302524008",
    "email": "vadlakondapranay03@gmail.com",
    "gstin": "22AAAAA0000A1Z5",
    "bank_name": "SBI Bank",
    "account_no": "325920621188",
    "ifsc": "SBIN0052",
    "upi_id": "6302524008@UPI",
    "signature_name": "P-HUB"
}

# =========================
# EMAIL CONFIG
# Use ONE Gmail account + ONE App Password
# Put your NEW app password here
# =========================
EMAIL_CONFIG = {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "sender_email": "vadlakondapranay03@gmail.com",
    "sender_password": "rmjbpamddoqdyaed"
}

# =========================
# SMS CONFIG (Twilio)
# =========================
SMS_CONFIG = {
    "enabled": False,
    "account_sid": "YOUR_TWILIO_ACCOUNT_SID",
    "auth_token": "YOUR_TWILIO_AUTH_TOKEN",
    "from_number": "+1XXXXXXXXXX"
}

# =========================
# DATABASE
# =========================
def get_db_connection():
    return pymysql.connect(
        host="localhost",
        user="root",
        password="Pranay",
        database="invoice_db",
        cursorclass=pymysql.cursors.DictCursor,
        autocommit=False
    )

# =========================
# HELPERS
# =========================
def to_decimal(value):
    return Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

def money(value):
    return f"₹{to_decimal(value):,.2f}"

def safe_str(value):
    return str(value).strip() if value is not None else ""

def format_date(dt_value):
    if isinstance(dt_value, datetime):
        return dt_value.strftime("%d-%m-%Y")
    try:
        return datetime.strptime(str(dt_value), "%Y-%m-%d %H:%M:%S").strftime("%d-%m-%Y")
    except Exception:
        return str(dt_value)

def validate_invoice_payload(data):
    required_fields = [
        "invoice_no",
        "customer_name",
        "subtotal",
        "gst_percent",
        "gst_amount",
        "grand_total",
        "items"
    ]

    for field in required_fields:
        if field not in data:
            return f"Missing required field: {field}"

    if not isinstance(data["items"], list) or len(data["items"]) == 0:
        return "Invoice must contain at least one item"

    for i, item in enumerate(data["items"], start=1):
        for key in ["description", "quantity", "rate", "amount"]:
            if key not in item:
                return f"Missing '{key}' in item {i}"

    return None

def fetch_invoice(invoice_id):
    connection = get_db_connection()
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM invoices WHERE id = %s", (invoice_id,))
            invoice = cursor.fetchone()

            if not invoice:
                return None, None

            cursor.execute(
                "SELECT * FROM invoice_items WHERE invoice_id = %s ORDER BY id ASC",
                (invoice_id,)
            )
            items = cursor.fetchall()
            return invoice, items
    finally:
        connection.close()

# =========================
# PDF HELPERS
# =========================
def draw_header(c, width, height):
    c.setFillColor(colors.HexColor("#0F172A"))
    c.rect(0, height - 95, width, 95, stroke=0, fill=1)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(40, height - 40, BUSINESS_INFO["name"])

    c.setFont("Helvetica", 9)
    c.drawString(40, height - 56, f"Address: {BUSINESS_INFO['address']}")
    c.drawString(40, height - 70, f"Phone: {BUSINESS_INFO['phone']}")
    c.drawString(
        40, height - 84,
        f"Email: {BUSINESS_INFO['email']}    GSTIN: {BUSINESS_INFO['gstin']}"
    )

    c.setFont("Helvetica-Bold", 24)
    c.drawRightString(width - 40, height - 48, "INVOICE")

def draw_footer(c, width):
    c.setStrokeColor(colors.HexColor("#CBD5E1"))
    c.line(40, 32, width - 40, 32)

    c.setFillColor(colors.HexColor("#475569"))
    c.setFont("Helvetica", 8)
    c.drawString(40, 20, f"Generated by {BUSINESS_INFO['name']}")
    c.drawRightString(width - 40, 20, f"Page {c.getPageNumber()}")

def draw_box(c, x, y, w, h, title, lines):
    c.setStrokeColor(colors.HexColor("#CBD5E1"))
    c.setFillColor(colors.white)
    c.roundRect(x, y - h, w, h, 8, stroke=1, fill=1)

    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x + 10, y - 18, title)

    text_y = y - 36
    c.setFont("Helvetica", 10)
    for line in lines:
        c.drawString(x + 10, text_y, safe_str(line))
        text_y -= 14

def draw_table_header(c, y):
    c.setFillColor(colors.HexColor("#E2E8F0"))
    c.rect(40, y - 18, 515, 20, stroke=0, fill=1)

    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(45, y - 5, "S.No")
    c.drawString(80, y - 5, "Description")
    c.drawString(300, y - 5, "Qty")
    c.drawString(380, y - 5, "Rate (₹)")
    c.drawString(470, y - 5, "Amount (₹)")

def draw_item_row(c, item, index, y):
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 10)

    row_top = y
    c.drawString(45, row_top, str(index))

    description = safe_str(item.get("description", ""))
    desc_lines = textwrap.wrap(description, width=36) or [""]
    desc_y = row_top
    for line in desc_lines:
        c.drawString(80, desc_y, line)
        desc_y -= 12

    c.drawString(300, row_top, safe_str(item.get("quantity", "")))
    c.drawRightString(455, row_top, f"{to_decimal(item.get('rate', 0)):,.2f}")
    c.drawRightString(545, row_top, f"{to_decimal(item.get('amount', 0)):,.2f}")

    row_height = max(18, len(desc_lines) * 12)
    c.setStrokeColor(colors.HexColor("#E2E8F0"))
    c.line(40, row_top - row_height + 4, 555, row_top - row_height + 4)

    return y - row_height

def draw_summary(c, x, y, invoice, cgst_amount, sgst_amount):
    box_w = 220
    box_h = 90

    c.setStrokeColor(colors.HexColor("#CBD5E1"))
    c.roundRect(x, y - box_h, box_w, box_h, 8, stroke=1, fill=0)

    c.setFont("Helvetica", 10)
    c.drawString(x + 12, y - 20, "Subtotal:")
    c.drawRightString(x + box_w - 12, y - 20, money(invoice["subtotal"]))

    half_gst = to_decimal(invoice["gst_percent"]) / 2
    c.drawString(x + 12, y - 40, f"CGST ({half_gst}%):")
    c.drawRightString(x + box_w - 12, y - 40, money(cgst_amount))

    c.drawString(x + 12, y - 60, f"SGST ({half_gst}%):")
    c.drawRightString(x + box_w - 12, y - 60, money(sgst_amount))

    c.setStrokeColor(colors.HexColor("#94A3B8"))
    c.line(x + 10, y - 70, x + box_w - 10, y - 70)

    c.setFont("Helvetica-Bold", 11)
    c.drawString(x + 12, y - 84, "Total Amount:")
    c.drawRightString(x + box_w - 12, y - 84, money(invoice["grand_total"]))

def generate_pdf(invoice_id, customer_phone="", customer_address="Customer Address"):
    invoice, items = fetch_invoice(invoice_id)
    if not invoice:
        return None

    pdf_path = os.path.join(PDF_FOLDER, f"invoice_{invoice_id}.pdf")
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    draw_header(c, width, height)

    y = height - 125
    draw_box(
        c, 40, y, 245, 80, "Bill To", [
            invoice["customer_name"],
            customer_address,
            f"Phone: {customer_phone or 'N/A'}"
        ]
    )

    invoice_date = invoice["invoice_date"]
    due_date_text = "Within 7 days"
    try:
        if isinstance(invoice_date, datetime):
            due_date_text = (invoice_date + timedelta(days=7)).strftime("%d-%m-%Y")
        else:
            parsed = datetime.strptime(str(invoice_date), "%Y-%m-%d %H:%M:%S")
            due_date_text = (parsed + timedelta(days=7)).strftime("%d-%m-%Y")
    except Exception:
        pass

    draw_box(
        c, 310, y, 245, 80, "Invoice Info", [
            f"Invoice Number: {invoice['invoice_no']}",
            f"Invoice Date: {format_date(invoice['invoice_date'])}",
            f"Due Date: {due_date_text}"
        ]
    )

    y = height - 250
    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Item Details")
    y -= 18

    draw_table_header(c, y)
    y -= 30

    for index, item in enumerate(items, start=1):
        if y < 170:
            draw_footer(c, width)
            c.showPage()
            draw_header(c, width, height)
            y = height - 120
            draw_table_header(c, y)
            y -= 30
        y = draw_item_row(c, item, index, y)

    gst_total = to_decimal(invoice["gst_amount"])
    cgst_amount = (gst_total / Decimal("2")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    sgst_amount = (gst_total / Decimal("2")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

    y -= 20
    draw_summary(c, 335, y, invoice, cgst_amount, sgst_amount)

    y -= 115
    draw_box(c, 40, y, 250, 90, "Payment Details", [
        f"Bank Name: {BUSINESS_INFO['bank_name']}",
        f"Account No: {BUSINESS_INFO['account_no']}",
        f"IFSC Code: {BUSINESS_INFO['ifsc']}",
        f"UPI ID: {BUSINESS_INFO['upi_id']}"
    ])

    draw_box(c, 305, y, 250, 90, "Terms & Conditions", [
        "Payment due within 7 days",
        "Late payment may incur charges",
        "Goods once sold will not be returned"
    ])

    y -= 120
    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(width - 50, y, "Authorized Signature")
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 50, y - 16, f"({BUSINESS_INFO['signature_name']})")

    draw_footer(c, width)
    c.save()
    return pdf_path

# =========================
# EMAIL + SMS
# =========================
def send_invoice_email(to_email, pdf_path, invoice, items):
    if not to_email:
        return "Email skipped (no customer email)"

    msg = EmailMessage()
    msg["Subject"] = f"Your Invoice {invoice['invoice_no']} from {BUSINESS_INFO['name']}"
    msg["From"] = EMAIL_CONFIG["sender_email"]
    msg["To"] = to_email

    body = f"""
Hello {invoice['customer_name']},

Thank you for your purchase.

Invoice Number: {invoice['invoice_no']}
Invoice Date: {format_date(invoice['invoice_date'])}
Total Amount: {money(invoice['grand_total'])}

Please find your invoice PDF attached.

Regards,
{BUSINESS_INFO['name']}
"""
    msg.set_content(body.strip())

    with open(pdf_path, "rb") as f:
        pdf_data = f.read()
        msg.add_attachment(
            pdf_data,
            maintype="application",
            subtype="pdf",
            filename=os.path.basename(pdf_path)
        )

    try:
        with smtplib.SMTP(EMAIL_CONFIG["smtp_server"], EMAIL_CONFIG["smtp_port"]) as server:
            server.starttls()
            server.login(EMAIL_CONFIG["sender_email"], EMAIL_CONFIG["sender_password"])
            server.send_message(msg)
        return "Email sent successfully"
    except Exception as e:
        return f"Email failed: {str(e)}"

def build_sms_message(invoice, items):
    item_count = len(items)
    return (
        f"{BUSINESS_INFO['name']}: Invoice {invoice['invoice_no']} generated. "
        f"Items: {item_count}, Total: {money(invoice['grand_total'])}, "
        f"Date: {format_date(invoice['invoice_date'])}. Thank you for your purchase."
    )

def send_sms(to_phone, message):
    if not to_phone:
        return "SMS skipped (no phone number)"
    if not SMS_CONFIG["enabled"]:
        return "SMS skipped (service disabled)"
    if not TWILIO_AVAILABLE:
        return "SMS skipped (twilio package not installed)"

    try:
        client = Client(SMS_CONFIG["account_sid"], SMS_CONFIG["auth_token"])
        client.messages.create(
            body=message,
            from_=SMS_CONFIG["from_number"],
            to=to_phone
        )
        return "SMS sent"
    except Exception as e:
        return f"SMS failed: {str(e)}"

# =========================
# PAGE ROUTES
# =========================
@app.route("/")
def home():
    return render_template("index.html")

@app.route("/invoices")
def invoices_page():
    return render_template("invoices.html")

# =========================
# SAVE INVOICE
# =========================
@app.route("/save_invoice", methods=["POST"])
def save_invoice():
    data = request.get_json(silent=True)

    if not data:
        return jsonify({"error": "Invalid or empty JSON payload"}), 400

    validation_error = validate_invoice_payload(data)
    if validation_error:
        return jsonify({"error": validation_error}), 400

    connection = None
    try:
        connection = get_db_connection()

        with connection.cursor() as cursor:
            invoice_date_obj = datetime.now()

            cursor.execute("""
                INSERT INTO invoices
                (invoice_no, customer_name, customer_email, invoice_date, subtotal, gst_percent, gst_amount, grand_total)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """, (
                safe_str(data["invoice_no"]),
                safe_str(data["customer_name"]),
                safe_str(data.get("customer_email", "")),
                invoice_date_obj,
                to_decimal(data["subtotal"]),
                to_decimal(data["gst_percent"]),
                to_decimal(data["gst_amount"]),
                to_decimal(data["grand_total"])
            ))

            invoice_id = cursor.lastrowid

            item_rows = []
            for item in data["items"]:
                item_rows.append((
                    invoice_id,
                    safe_str(item["description"]),
                    int(item["quantity"]),
                    to_decimal(item["rate"]),
                    to_decimal(item["amount"])
                ))

            cursor.executemany("""
                INSERT INTO invoice_items (invoice_id, description, quantity, rate, amount)
                VALUES (%s, %s, %s, %s, %s)
            """, item_rows)

        connection.commit()

        return jsonify({
            "message": "Invoice saved successfully",
            "invoice_id": invoice_id
        }), 201

    except Exception as e:
        if connection:
            connection.rollback()
        return jsonify({"error": str(e)}), 500

    finally:
        if connection:
            connection.close()

# =========================
# DOWNLOAD PDF
# =========================
@app.route("/download_pdf/<int:invoice_id>")
def download_pdf(invoice_id):
    try:
        customer_phone = request.args.get("customer_phone", "")
        customer_address = request.args.get("customer_address", "Customer Address")
        pdf_path = generate_pdf(invoice_id, customer_phone, customer_address)

        if not pdf_path:
            return "Invoice not found", 404

        return send_file(pdf_path, as_attachment=True)
    except Exception as e:
        return str(e), 500

# =========================
# SEND EMAIL + SMS
# =========================
@app.route("/send_invoice/<int:invoice_id>", methods=["POST"])
def send_invoice(invoice_id):
    try:
        data = request.get_json(silent=True) or {}
        customer_phone = safe_str(data.get("customer_phone", ""))
        customer_address = safe_str(data.get("customer_address", "Customer Address"))

        invoice, items = fetch_invoice(invoice_id)
        if not invoice:
            return jsonify({"error": "Invoice not found"}), 404

        pdf_path = generate_pdf(invoice_id, customer_phone, customer_address)
        if not pdf_path or not os.path.exists(pdf_path):
            return jsonify({"error": "Failed to generate PDF"}), 500

        email_status = send_invoice_email(
            invoice.get("customer_email", ""),
            pdf_path,
            invoice,
            items
        )

        sms_status = send_sms(
            customer_phone,
            build_sms_message(invoice, items)
        )

        return jsonify({
            "message": "Invoice sending completed",
            "email_status": email_status,
            "sms_status": sms_status
        }), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500

# =========================
# GET ALL INVOICES
# =========================
@app.route("/get_invoices")
def get_invoices():
    connection = None
    try:
        connection = get_db_connection()
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM invoices ORDER BY id DESC")
            invoices = cursor.fetchall()
        return jsonify(invoices)

    except Exception as e:
        return jsonify({"error": str(e)}), 500

    finally:
        if connection:
            connection.close()

if __name__ == "__main__":
    app.run(debug=True)   